"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dnyck!w&(=evl0+=(!&a(%*n^uy)m)3#sw0=9=w)ni87u4k!bf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "192.168.15.250"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "coreTube",
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

#
# Lista de domínios que podem fazer requisições para sua API.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3003",
    "http://localhost:8080",
    "http://localhost:3000",
    "http://localhost:80",
    "http://localhost",

    'http://54.94.172.107:80',
    "http://54.94.172.107:88",

    "http://192.168.0.250:3000",
    "http://192.168.0.250:3001",
    "http://192.168.0.250:3002",
    "http://192.168.0.250:3003",
    "http://192.168.0.250:8000",
    "http://192.168.15.134:3003",
    "http://192.168.15.134:88",
    "http://192.168.15.134:8080",
    "http://192.168.15.250:8080",
    "http://192.168.15.250:80",
    "http://192.168.15.250",
]
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Se tiver 'True' Libera qualquer origem. (não só as da lista)
CORS_ALLOW_ALL_ORIGINS = True

# Permite enviar cookies, headers de autenticação ou credenciais com a requisição.
# Útil se você usa login por sessão ou precisa mandar Authorization.
CORS_ALLOW_CREDENTIALS = True

# Define quais headers o navegador pode enviar.
CORS_ALLOW_HEADERS = [
    'content-type',   # permite enviar JSON.
    'X-CSRFToken',    # usado em autenticação por sessão.
    'Authorization',  # necessário para JWT, senão o preflight bloqueia.
]

# Lista de métodos HTTP permitidos.
CORS_ALLOW_METHODS = [
    'GET', 'POST', 'PUT',
    'PATCH', 'DELETE', 'OPTIONS',
]

# Diz que o cookie de sessão pode ser enviado em HTTP (não só HTTPS).
# Em produção, deve ser True.
SESSION_COOKIE_SECURE = False

# Permite que cookies de sessão sejam enviados mesmo em requisições cross-site.
# (Se fosse "Lax" ou "Strict", bloquearia em alguns cenários).
SESSION_COOKIE_SAMESITE = None

# Mesma lógica, mas para o cookie de CSRF.
CSRF_COOKIE_SAMESITE = None

# Permite CSRF cookie em HTTP.
# ⚠️ Em produção, deve ser True.
CSRF_COOKIE_SECURE = True

# Se fosse True, o cookie CSRF não poderia ser acessado via JavaScript.
# Como está False, o JS pode ler.
CSRF_COOKIE_HTTPONLY = True

# Libera o acesso para o adm do django
# Define o domínio válido para o cookie CSRF.
# Isso significa que o cookie só será aceito se vier desse domínio.
CSRF_COOKIE_DOMAIN = '192.168.15.250'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.SessionAuthentication',  # exigir CSRF
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # Define que todas as views exigem login por padrão
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'StandResultsPagination',
    'PAGE_SIZE': 50,

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter']
}
# Configura o tempo de vido do token de login.
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),   # token de acesso dura 120 minutos
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),      # token de refresh dura 7 dias
}